# Generated by Django 4.2.16 on 2024-12-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
