# Generated by Django 4.2.16 on 2024-12-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_report_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
